### ISSUE TITLE
chose best unit for measurements in time, distance etc

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm-shiny-prototype#2]
data summary and plot should have best unit adjusted according to dat range.

- wait for `units` package [support of user defined units](https://github.com/edzer/units/pull/31)
- option to turn it on/off
- somewhat related: `ddays(6) + dhours(8)`  usage of lubridate to replace current manual conversion on time?
- the variogram fit control changing unit with scale. option to keep it fixed or show two values?

**Comment by chfleming** [comment]
1. Right now everything is in SI units internally.
2. I throw these numbers into the internal unit() function with a dimension specification and it chooses the most parsimonious units and gives its labeling and scaling information.
3. I then have unit.class() functions that can convert the units on all of my class objects (This naming is bad, unit() should be pick_units() and unit.class() should be convert_units.class())
4. So before plotting or printing, I run my objects/numbers through these functions and then on the plot axes or pasted to the print I include the labeling character string from unit().

Using unit structures seems much more cumbersome than what we need, because we will always be either (1) converting SI units to parsimonious units right before display or (2) sticking with SI units.

The only step that I think could be simplified would to be able to plot objects in their internal SI units and then do unit conversion on the axes. This would trade the task of converting multiple plotted objects for one axis conversion. I could not figure out how to do this in base plot without disrupting the axis formatting, but it looks possible in gg_plot with the scales package.

**Comment by xhdong-umd** [comment]
Based on my limited understanding now, the problem my ggplot2 plots are based on data frame instead of object. If I change the unit before plotting, I changed the values in data frame, then I need to associate the changed value with the current unit somewhere. With a object it's easy to carry a unit label, but for the data frame I need to keep the unit label somewhere, maybe outside of the data frame. 

With `scales` it should be possible to just change the axes label without changing the value, then I also have the need for changing units other than plot axes, like the time range summary from the time subsetting page. If I changed the internal value before, I need to get the unit label somewhere. If I used `scales` without changing internal value, I need to convert the value again with a different function.

I also feel `units` usage are trying too much to make units look natural, our model fitting and all heavy computing will definitely not using it. All I really want is actually some approach to associate the value with a unit label, then some general methods can be used in plots and summaries. This can be done in object with attributes. I can also add a column of unit label in data frame, but that will have too much redundancy. Maybe I can use ggplot with a object that is data.frame with some attribute slots? 

I will look at the ctmm code and think about my options then update here.

**Comment by xhdong-umd** [comment]
After reviewing `units` package and our needs in the app, I decided to just use existing methods. Turned out the `scales` for `ggplot` is easy to work with. I just pick the best unit, then feed the function to ggplot then I have the axes in correct label without need of changing internal values.

```r
by_best_unit <- function(data, dimension, thresh = 1, concise = FALSE) {
  test <- ctmm:::unit(data, dimension, thresh = thresh, concise = concise)
  # scale to be used by `scales` package, which is reversed.
  return(list(value = data / test$scale, unit = test$name, scale = 1 / test$scale))
}

format_best_unit <- function(test_value, dimension) {
  best_unit <- by_best_unit(test_value, dimension, concise = TRUE)
  unit_format(unit = best_unit$unit, scale = best_unit$scale, digits = 2)
}
```

Then I used similar method on the data summary table and got the result I want.

I think Justin wanted to have a switch to turn the unit conversion on and off. So you want a checkbox in all plots, data summary tables, anywhere with unit conversion? 

One thing to notice is that the raw value for time could be quite big, for example the time range years will be represented in seconds.

**Comment by chfleming** [comment]
In the plots it is not important to have the option for raw units. I would not implement that feature.

In the model and home-range summaries/reports this option becomes important. Raw units makes it easier for people working with many individuals (possibly of different species) to make comparisons.

**Comment by xhdong-umd** [comment]
I implemented units conversion for distance, time in plots and all summaries. Added switch for seconds/normalized units in the data summary table. Will add similar switches in summaries/reports when needed.
